import { Project } from "./types";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "supabase",
    name: "Supabase",
    description: "The open source Firebase alternative. Supabase is an open source Firebase alternative providing all the backend features you need to build a product: a Postgres database, Authentication, instant APIs, Edge Functions, Realtime subscriptions, and Storage.",
    url: "https://github.com/supabase/supabase",
    tags: ["Backend", "Database", "Auth", "PostgreSQL", "SaaS-Alternative:Firebase"],
    language: "TypeScript",
    stars: 68400,
    forks: 5300,
    license: "Apache-2.0",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.8,
    ratingCount: 142,
    upvotes: 215,
    createdAt: new Date("2026-01-01T12:00:00Z").toISOString(),
    updatedAt: new Date("2026-05-30T15:30:00Z").toISOString()
  },
  {
    id: "appflowy",
    name: "AppFlowy",
    description: "AppFlowy is an open-source alternative to Notion. You are in charge of your data and customizations. Built with Flutter and Rust, designed for offline-first and private workspaces.",
    url: "https://github.com/AppFlowy-IO/AppFlowy",
    tags: ["Productivity", "Notes", "Workspace", "Offline-First", "SaaS-Alternative:Notion"],
    language: "Rust",
    stars: 48900,
    forks: 3400,
    license: "AGPL-3.0",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.6,
    ratingCount: 98,
    upvotes: 185,
    createdAt: new Date("2026-01-10T08:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-01T10:00:00Z").toISOString()
  },
  {
    id: "calcom",
    name: "Cal.com",
    description: "Scheduling infrastructure for everyone. Cal.com is an open-source alternative to Calendly. It is highly customizable, white-labelable, and supports self-hosting, enterprise integrations, and rich APIs.",
    url: "https://cal.com",
    tags: ["Scheduling", "Calendar", "API", "Business", "SaaS-Alternative:Calendly"],
    language: "TypeScript",
    stars: 31200,
    forks: 2900,
    license: "AGPL-3.0",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.7,
    ratingCount: 74,
    upvotes: 140,
    createdAt: new Date("2026-01-15T15:20:00Z").toISOString(),
    updatedAt: new Date("2026-06-02T11:45:00Z").toISOString()
  },
  {
    id: "penpot",
    name: "Penpot",
    description: "The first open source design and prototyping platform. Penpot is the open-source alternative to Figma, enabling designers and developers to collaborate in real-time using open web standards like SVG.",
    url: "https://penpot.app",
    tags: ["Design", "Prototyping", "Collaboration", "Vector", "SaaS-Alternative:Figma"],
    language: "Clojure",
    stars: 27500,
    forks: 1400,
    license: "AGPL-3.0",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.5,
    ratingCount: 63,
    upvotes: 120,
    createdAt: new Date("2026-01-20T10:50:00Z").toISOString(),
    updatedAt: new Date("2026-06-03T09:15:00Z").toISOString()
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Fair-code workflow automation tool. n8n is an extendable workflow automation tool with a node-based editor, acting as an open source alternative to Zapier. It lets you connect APIs, databases, and LLMs without hassle.",
    url: "https://n8n.io",
    tags: ["Automation", "Workflow", "Integrations", "SaaS-Alternative:Zapier"],
    language: "TypeScript",
    stars: 42100,
    forks: 5100,
    license: "Sustainable-Use",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.8,
    ratingCount: 110,
    upvotes: 210,
    createdAt: new Date("2026-02-01T14:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-04T16:00:00Z").toISOString()
  },
  {
    id: "plausible",
    name: "Plausible Analytics",
    description: "Simple, open-source, lightweight and privacy-friendly web analytics. Plausible is an lightweight alternative to Google Analytics that does not use cookies and is fully GDPR, CCPA and PECR-compliant out of the box.",
    url: "https://github.com/plausible/analytics",
    tags: ["Analytics", "Privacy", "Marketing", "SaaS-Alternative:GoogleAnalytics"],
    language: "Elixir",
    stars: 18500,
    forks: 1100,
    license: "AGPL-3.0",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.6,
    ratingCount: 52,
    upvotes: 95,
    createdAt: new Date("2026-02-10T11:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-05T08:30:00Z").toISOString()
  },
  {
    id: "ghost",
    name: "Ghost",
    description: "An independent, open source blogging and publishing platform. Deployed as a modern Node.js CMS that lets creators turn their audience into a business with newsletters, memberships, and paid subscripts.",
    url: "https://github.com/TryGhost/Ghost",
    tags: ["CMS", "Publishing", "Blog", "Newsletters", "SaaS-Alternative:Substack"],
    language: "JavaScript",
    stars: 45700,
    forks: 9800,
    license: "MIT",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.7,
    ratingCount: 88,
    upvotes: 153,
    createdAt: new Date("2026-02-15T09:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-06T12:00:00Z").toISOString()
  },
  {
    id: "activepieces",
    name: "Activepieces",
    description: "Your open-source Zapier. Activepieces is a user-friendly workflow builder and AI automated integrator. Built for teams who demand secure, self-hosted and highly customizable automation integrations.",
    url: "https://github.com/activepieces/activepieces",
    tags: ["Automation", "Workflow", "No-Code", "SaaS-Alternative:Zapier"],
    language: "TypeScript",
    stars: 8700,
    forks: 920,
    license: "MIT",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.4,
    ratingCount: 22,
    upvotes: 45,
    createdAt: new Date("2026-03-01T10:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-07T14:20:00Z").toISOString()
  },
  {
    id: "chatwoot",
    name: "Chatwoot",
    description: "Open-source customer relationship suite and live chat. Chatwoot is a great self-hostable alternative to Intercom, Zendesk, or Drift. It bundles modern team inboxes, live chat, automation, and chatbot support.",
    url: "https://github.com/chatwoot/chatwoot",
    tags: ["Support", "Customer", "LiveChat", "Inbox", "SaaS-Alternative:Intercom"],
    language: "Ruby",
    stars: 19800,
    forks: 3100,
    license: "MIT",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.5,
    ratingCount: 46,
    upvotes: 82,
    createdAt: new Date("2026-03-05T13:45:00Z").toISOString(),
    updatedAt: new Date("2026-06-08T09:10:00Z").toISOString()
  },
  {
    id: "focalboard",
    name: "Focalboard",
    description: "Focalboard is an open source, multilingual self-hosted alternative to Trello, Notion, and Asana. It helps individuals and teams organize tasks in beautiful Kanban boards, calendar lists, and tables.",
    url: "https://github.com/mattermost/focalboard",
    tags: ["Project-Management", "Kanban", "Tasks", "SaaS-Alternative:Trello"],
    language: "Go",
    stars: 21300,
    forks: 1800,
    license: "AGPL-3.0",
    type: "open-source",
    submitterId: "system",
    submitterName: "OpenAlt Core",
    rating: 4.3,
    ratingCount: 41,
    upvotes: 68,
    createdAt: new Date("2026-03-12T08:15:00Z").toISOString(),
    updatedAt: new Date("2026-06-09T15:00:00Z").toISOString()
  }
];

export const ALTERNATIVE_MAP: Record<string, string[]> = {
  "firebase": ["supabase"],
  "notion": ["appflowy"],
  "calendly": ["calcom"],
  "figma": ["penpot"],
  "zapier": ["n8n", "activepieces"],
  "google analytics": ["plausible"],
  "substack": ["ghost"],
  "medium": ["ghost"],
  "intercom": ["chatwoot"],
  "trello": ["focalboard"],
  "asana": ["focalboard"]
};
